<?php

return [
    App\Providers\AppServiceProvider::class,
    App\Providers\BeritaServiceProvider::class,
    App\Providers\BlogServiceProvider::class,
    App\Providers\EkstrakurikulerServiceProvider::class,
    App\Providers\FasilitasServiceProvider::class,
    App\Providers\GaleriServiceProvider::class,
    App\Providers\GuruServiceProvider::class,
    App\Providers\KategoriBeritaServiceProvider::class,
    App\Providers\KategoriPengumumanServiceProvider::class,
    App\Providers\KelasServiceProvider::class,
    App\Providers\KritikSaranServiceProvider::class,
    App\Providers\MataPelajaranServiceProvider::class,
    App\Providers\PengumumanServiceProvider::class,
    App\Providers\PrestasiServiceProvider::class,
    App\Providers\SiswaServiceProvider::class,
    App\Providers\StafServiceProvider::class,
    App\Providers\StrukturOrganisasiServiceProvider::class,
    App\Providers\UserServiceProvider::class,
    App\Providers\WelcomeServiceProvider::class,
    RealRashid\SweetAlert\SweetAlertServiceProvider::class,
    Maatwebsite\Excel\ExcelServiceProvider::class,
];
